baseURL = 'https://contents.mikiri.net/'

languageCode = 'en-us'
title = 'contents.mikiri.net'
hasCJKLanguage = true

theme = "contents_mikiri_net"


[[deployment.targets]]
  name = "aws"
  URL = "s3://contents.mikiri.net?region=ap-southeast-1"


[[deployment.targets]]
  name = "gcs"
  URL = "gs://contents.mikiri.net"